export const hotelData = [
  {
    image: "https://shorturl.at/fgtO0",
    name: "Aparthotel Stare Miasto",
    city: "Madrid",
    price: "120",
    rating: 8.9,
    feedback: "Excellent",
  },
  {
    image: "https://shorturl.at/ntGI7",
    name: "Luxury Suites",
    city: "Paris",
    price: "250",
    rating: 9.5,
    feedback: "Exceptional",
  },
  {
    image: "https://shorturl.at/gzBO4",
    name: "Harbor View Hotel",
    city: "Sydney",
    price: "180",
    rating: 8.7,
    feedback: "Great",
  },
  {
    image:
      "https://img.freepik.com/free-psd/luxury-beach-house-generative-ai_587448-2221.jpg",
    name: "Mountain Retreat",
    city: "Vancouver",
    price: "200",
    rating: 9.0,
    feedback: "Superb",
  },
  {
    image:
      "https://img.freepik.com/free-photo/nature-water-beautiful-blue-house_1203-4911.jpg",
    name: "Seaside Resort",
    city: "Miami",
    price: "160",
    rating: 8.5,
    feedback: "Very Good",
  },
  {
    image: "https://rb.gy/ocdbq4",
    name: "Downtown Suites",
    city: "New York",
    price: "220",
    rating: 9.1,
    feedback: "Outstanding",
  },
  {
    image: "https://rb.gy/qjddml",
    name: "Modern City Hotel",
    city: "Tokyo",
    price: "190",
    rating: 8.8,
    feedback: "Excellent",
  },
  {
    image: "https://rb.gy/0604mu",
    name: "Historic Inn",
    city: "London",
    price: "170",
    rating: 8.6,
    feedback: "Great",
  },
  {
    image: "https://rb.gy/lq8h4m",
    name: "Riverside Lodge",
    city: "Amsterdam",
    price: "210",
    rating: 9.2,
    feedback: "Superb",
  },
  {
    image: "https://rb.gy/2ng5of",
    name: "Skyline Suites",
    city: "San Francisco",
    price: "230",
    rating: 9.4,
    feedback: "Exceptional",
  },
];
